#pragma once
#include <string>

/* generated by ./script/configure-file.py using template
 * src/adapter/writematrix/manpage.hpp.in with data src/adapter/writematrix/manpage.1.pre.
 * Manual edits will be OVERWRITTEN UNCONDITIONALLY. */

namespace dptk {
std::string manpage
  = R"V0G0N(WRITE-MATRIX(1)           Dispersion Toolkit Manuals           WRITE-MATRIX(1)

NAME
       write-matrix - writes as a matrix of points

SYNOPSIS
       write-matrix  [-ts]  [--i  FILE]  [--o  FILE]  [--transpose]  [--delim‐
       iter=CHARACTER] [--silent]

DESCRIPTION
       Writes as a matrix of points, where each column corresponds to  a  dis‐
       tinct dimension, and where each row represents a point.

OPTIONS
       --i FILE, --i=FILE
              Retrieves  a point set from FILE.  Its absence is substituted by
              stdin.

       --o FILE, --o=FILE
              Redirects the point set sequence to FILE,  opened  in  overwrite
              mode  (not appending mode).  Without FILE, results are forwarded
              to stdout.  Errors encountered during  the  program’s  execution
              are streamed into stderr, and not into either stdout or FILE.

       --transpose, -t
              Transpose the matrix before writing to output stream.

       --delimiter=CHARACTER
              A point set’s coordinates are separated by CHARACTER, while each
              point resides on a distinct line.  Recommended condition:  CHAR‐
              ACTER = ' ', CHARACTER = '\t'.

       --silent, -s
              Suppress  comments  in the output stream, yielding only the com‐
              puted value.  The latter could be the point set or its cardinal‐
              ity.

LIMITATION
       The algorithm requires a point set, not a point set sequence.

AUTHORS
       Benjamin Sommer.

1.1.0                          December 18, 2020               WRITE-MATRIX(1)
)V0G0N";
}
