#!/bin/python

import sys

src_path = sys.argv[1]
tpl_path = sys.argv[2]
var_name = sys.argv[3]

with open(src_path) as f:
  src = f.read()
with open(tpl_path) as f:
  tpl = f.read()

generator = "generator"
generator_message = f"generated by {sys.argv[0]} using template {tpl_path} with data {src_path}. Manual edits will be OVERWRITTEN UNCONDITIONALLY."

dst = tpl % {var_name : src, generator : generator_message }
print(dst)