SET(FLAGS_SSE2  "-msse2")
SET(FLAGS_SSE3  "-msse3")
SET(FLAGS_SSSE3 "-mssse3")
SET(FLAGS_SSE41 "-msse4.1")
SET(FLAGS_SSE42 "-msse4.2")
SET(FLAGS_AVX   "-mavx")
SET(FLAGS_AVX2  "-mf16c -mavx2 -mfma -mlzcnt -mabm -mbmi -mbmi2")
SET(FLAGS_NATIVE "-march=native")

SET(CMAKE_CXX_COMPILER "g++")
SET(CMAKE_C_COMPILER "gcc")
SET(CMAKE_C_FLAGS_DEBUG "-DDEBUG")
SET(CMAKE_CXX_FLAGS "-fPIC -w")
SET(CMAKE_CXX_FLAGS_DEBUG          "-DDEBUG  -g -O0 -ftree-ter")
SET(CMAKE_CXX_FLAGS_RELEASE        "-DNDEBUG    -O3 -march=native -Wstrict-aliasing=0 -ffast-math")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-DNDEBUG -g -O3 -Wstrict-aliasing=0 ")
SET(CMAKE_EXE_LINKER_FLAGS "")
